### ISSUE TITLE
Any plans to upgrade and keep the project updated in the future?

### ISSUE THREAD

**Issue by xergioalexpro** [crisp-oss/chappe#7]
Hi, I'm Sergio Florez CTO at [DailyBot](https://www.dailybot.com/).

I was analyzing this Developer Docs Builder and I loved it. I've been considering using it in our product, but I was looking at the dependencies and noticed that it uses Gulp (which hasn't been updated in 3 years) and other pretty outdated libraries.

Are there any plans to upgrade to other more up-to-date libraries and keep the project up to date?

I am worried that at some point the project will die because of it, so I would refrain from using it.

Thanks,

**Comment by valeriansaliou** [comment]
Hey Sergio,

Thanks! We built this for Crisp (at https://docs.crisp.chat/), so this is long-term and actively maintained.

Some dependencies are outdated, but that does not mean Chappe will stop working in the future. Worst case, some libraries stop working looking forward w/ a future NodeJS version, in which case we would find an alternative. We use Gulp for all our projects internally, and it's been working great for 5+ years for now (just made the move to Gulp 3).

I think you can use it w/o any issue, Crisp relies on Chappe for business-critical features, so Chappe is definitely going to be supported long-term.

Valerian.

**Comment by xergioalexpro** [comment]
Hey Valerian,

Thanks for your quick reply. This is very good news and it sounds pretty good to know that it will be supported in long-term.

I was also quite worried about the outdated libraries due to security vulnerabilities, but since it will be a separate website to our product we can live with it.
We'll give it a try and improve our public developer docs with Chappe.

I will share the url when we have it ready in case you can add us in the Readme.

Thanks,

**Comment by valeriansaliou** [comment]
If there were any critical security vulnerabilities, they would be scoped to the system you use to build the static assets, so this vulnerability would not be able to propagate to your production systems.

You'd typically use a CI/CD sandboxed runner or Cloudflare Pages / Netlify / others which would produce static assets w/ no runtime.

**Comment by xergioalexpro** [comment]
Sure, you're right. It's just that we're very meticulous about reviewing any new technology or library that we start using.

Thanks,
